<?php

namespace Database\Seeders;

use App\Models\FeatureCategory;
use App\Models\FeatureCategoryItem;
use Illuminate\Database\Seeder;

class FeatureCategorySeeder extends Seeder
{
    /**
     * Seed the feature categories and their items.
     * Maps to existing Feature model's 'name' column for access control.
     */
    public function run(): void
    {
        // Clear existing data
        FeatureCategoryItem::query()->delete();
        FeatureCategory::query()->delete();

        // ═══════════════════════════════════════════════════
        // CATEGORY 1: Kasir & Penjualan
        // ═══════════════════════════════════════════════════
        $cat1 = FeatureCategory::create([
            'name'            => 'Kasir & Penjualan',
            'slug'            => 'sales-pos',
            'description'     => 'Kelola transaksi harian, riwayat penjualan, dan piutang pelanggan',
            'icon_type'       => 'phosphor',
            'icon_value'      => 'ph-storefront',
            'icon_color'      => '#F44336',
            'gradient_from'   => '#F44336',
            'gradient_to'     => '#E91E63',
            'is_active'       => true,
            'is_collapsible'  => true,
            'is_default_open' => true,
            'sort_order'      => 1,
            'layout_style'    => 'grid',
        ]);

        $this->seedItems($cat1->id, [
            [
                'feature_key'    => 'pos',
                'permission_key' => 'akses pos',
                'route_name'     => 'pos.index',
                'label'          => 'Point of Sale',
                'description'    => 'Catat penjualan dengan cepat.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-storefront',
                'icon_bg_color'  => '#F44336',
                'sort_order'     => 1,
                'data_step'      => '1',
                'data_title'     => 'Kasir Pintar (POS)',
                'data_intro'     => '<strong>Catat penjualan dengan cepat.</strong> Ini adalah jantung bisnis Anda. Masukkan pesanan, pilih metode pembayaran, dan cetak nota dalam hitungan detik.',
            ],
            [
                'feature_key'       => null,
                'permission_key'    => null,
                'route_name'        => 'reseller-products.index',
                'label'             => 'Produk Reseller',
                'description'       => 'Barang siap jual dari pusat.',
                'icon_type'         => 'phosphor',
                'icon_value'        => 'ph-package',
                'icon_bg_color'     => '#1E88E5',
                'sort_order'        => 2,
                'special_condition' => 'isReseller',
                'data_title'        => 'Produk Reseller',
                'data_intro'        => '<strong>Barang siap jual dari pusat.</strong> Terima dan kelola stok barang yang Anda beli dari outlet pusat di sini.',
            ],
            [
                'feature_key'    => 'sales_management',
                'permission_key' => 'lihat penjualan',
                'route_name'     => 'sales.index',
                'label'          => 'Penjualan',
                'description'    => 'Pantau semua transaksi.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-receipt',
                'icon_bg_color'  => '#E91E8C',
                'sort_order'     => 3,
                'data_step'      => '2',
                'data_title'     => 'Riwayat Penjualan',
                'data_intro'     => '<strong>Pantau semua transaksi.</strong> Lihat daftar nota yang keluar, cek histori pesanan pelanggan, atau batalkan transaksi jika terjadi kesalahan.',
            ],
            [
                'feature_key'    => 'discount_management',
                'permission_key' => 'lihat diskon',
                'route_name'     => 'discounts.index',
                'label'          => 'Diskon',
                'description'    => 'Menangkan hati pelanggan.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-ticket',
                'icon_bg_color'  => '#AB47BC',
                'sort_order'     => 4,
                'data_step'      => '3',
                'data_title'     => 'Promo & Diskon',
                'data_intro'     => '<strong>Menangkan hati pelanggan.</strong> Buat berbagai promo menarik seperti diskon persentase atau \'Beli 1 Gratis 1\' untuk meningkatkan omzet Anda.',
            ],
            [
                'feature_key'    => 'invoice_list',
                'permission_key' => 'lihat invoice',
                'route_name'     => 'invoices.index',
                'label'          => 'Daftar Invoice',
                'description'    => 'Pantau tagihan & transaksi.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-invoice',
                'icon_bg_color'  => '#1E88E5',
                'sort_order'     => 5,
                'data_step'      => '7.5',
                'data_title'     => 'Ringkasan Invoice',
                'data_intro'     => '<strong>Pantau tagihan & transaksi.</strong> Lihat ringkasan terbaru dari penjualan, pemasukan, pengeluaran, dan piutang dalam satu tampilan cepat.',
            ],
            [
                'feature_key'    => 'customer_management',
                'permission_key' => 'lihat pelanggan',
                'route_name'     => 'customer-debts.index',
                'label'          => 'Pelanggan & Piutang',
                'description'    => 'Hubungan pelanggan.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-hand-coins',
                'icon_bg_color'  => '#00897B',
                'sort_order'     => 6,
                'data_step'      => '23',
                'data_title'     => 'Pelanggan & Piutang',
                'data_intro'     => '<strong>Hubungan pelanggan.</strong> Simpan database pelanggan setia dan pantau catatan piutang (bon) agar tidak ada yang terlewat ditagih.',
            ],
        ]);

        // ═══════════════════════════════════════════════════
        // CATEGORY 2: Keuangan & Arus Kas
        // ═══════════════════════════════════════════════════
        $cat2 = FeatureCategory::create([
            'name'            => 'Keuangan & Arus Kas',
            'slug'            => 'finance-cashflow',
            'description'     => 'Pantau uang masuk, keluar, dan atur metode pembayaran outlet',
            'icon_type'       => 'phosphor',
            'icon_value'      => 'ph-trend-up',
            'icon_color'      => '#7E57C2',
            'gradient_from'   => '#7E57C2',
            'gradient_to'     => '#5E35B1',
            'is_active'       => true,
            'is_collapsible'  => true,
            'is_default_open' => true,
            'sort_order'      => 2,
            'layout_style'    => 'grid',
        ]);

        $this->seedItems($cat2->id, [
            [
                'feature_key'    => 'finance_management',
                'permission_key' => 'lihat keuangan',
                'route_name'     => 'finance.index',
                'label'          => 'Keuangan',
                'description'    => 'Kesehatan finansial outlet.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-trend-up',
                'icon_bg_color'  => '#7E57C2',
                'sort_order'     => 1,
                'data_step'      => '4',
                'data_title'     => 'Arus Kas (Keuangan)',
                'data_intro'     => '<strong>Kesehatan finansial outlet.</strong> Pantau seluruh uang masuk dan keluar. Pastikan saldo kas Anda selalu cocok dengan kondisi di lapangan.',
            ],
            [
                'feature_key'    => 'other_income',
                'permission_key' => 'buat pemasukan',
                'route_name'     => 'expenses.index',
                'route_params'   => ['type' => 'income'],
                'label'          => 'Pemasukan Lain',
                'description'    => 'Catat uang masuk tambahan.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-coins',
                'icon_bg_color'  => '#26A69A',
                'sort_order'     => 2,
                'data_step'      => '5',
                'data_title'     => 'Pemasukan Lain',
                'data_intro'     => '<strong>Catat uang masuk tambahan.</strong> Masukkan pendapatan di luar hasil jualan kasir agar laporan keuangan Anda tetap akurat dan jujur.',
            ],
            [
                'feature_key'    => 'operational_costs',
                'permission_key' => 'buat pengeluaran',
                'route_name'     => 'expenses.index',
                'route_params'   => ['type' => 'expense'],
                'label'          => 'Biaya Ops',
                'description'    => 'Catat pengeluaran Anda.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-money-wavy',
                'icon_bg_color'  => '#FFA726',
                'sort_order'     => 3,
                'data_step'      => '6',
                'data_title'     => 'Biaya Operasional',
                'data_intro'     => '<strong>Catat pengeluaran Anda.</strong> Masukkan biaya listrik, sewa, gaji, hingga belanja kecil lainnya untuk mengetahui sisa untung bersih Anda.',
            ],
            [
                'feature_key'    => 'balance_withdrawal',
                'permission_key' => 'buat penarikan',
                'route_name'     => 'withdraw.index',
                'label'          => 'Penarikan Saldo',
                'description'    => 'Ambil dana Anda.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-bank',
                'icon_bg_color'  => '#43A047',
                'sort_order'     => 4,
                'data_step'      => '7',
                'data_title'     => 'Tarik Saldo',
                'data_intro'     => '<strong>Ambil dana Anda.</strong> Ajukan penarikan saldo hasil pembayaran nontunai ke rekening bank atau dompet digital pribadi Anda.',
            ],
            [
                'feature_key'    => 'payment_methods',
                'permission_key' => 'lihat metode pembayaran',
                'route_name'     => 'outlet-payment-links.index',
                'label'          => 'Metode Pembayaran',
                'description'    => 'Atur opsi pembayaran.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-scan',
                'icon_bg_color'  => '#8E24AA',
                'sort_order'     => 5,
                'data_step'      => '8',
                'data_title'     => 'Metode Pembayaran',
                'data_intro'     => '<strong>Atur opsi pembayaran.</strong> Hubungkan dompet digital atau rekening bank Anda agar pelanggan bisa membayar dengan QRIS atau transfer.',
            ],
        ]);

        // ═══════════════════════════════════════════════════
        // CATEGORY 3: Produk & Inventori
        // ═══════════════════════════════════════════════════
        $cat3 = FeatureCategory::create([
            'name'            => 'Produk & Inventori',
            'slug'            => 'product-inventory',
            'description'     => 'Kelola menu, resep, stok bahan baku, dan proses produksi',
            'icon_type'       => 'phosphor',
            'icon_value'      => 'ph-bowl-steam',
            'icon_color'      => '#FB8C00',
            'gradient_from'   => '#FB8C00',
            'gradient_to'     => '#F4511E',
            'is_active'       => true,
            'is_collapsible'  => true,
            'is_default_open' => true,
            'sort_order'      => 3,
            'layout_style'    => 'grid',
        ]);

        $this->seedItems($cat3->id, [
            [
                'feature_key'    => 'products_recipes',
                'permission_key' => 'lihat produk',
                'route_name'     => 'products-hpp.index',
                'label'          => 'Produk & Resep',
                'description'    => 'Atur menu jualan Anda.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-bowl-steam',
                'icon_bg_color'  => '#FB8C00',
                'sort_order'     => 1,
                'data_step'      => '12',
                'data_title'     => 'Menu & Resep',
                'data_intro'     => '<strong>Atur menu jualan Anda.</strong> Masukkan resep rahasia Anda di sini, sistem akan menghitung biaya produksi (HPP) secara otomatis.',
            ],
            [
                'feature_key'    => 'raw_materials',
                'permission_key' => 'lihat bahan baku',
                'route_name'     => 'raw-materials.index',
                'label'          => 'Bahan Baku',
                'description'    => 'Jangan sampai kehabisan.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-warehouse',
                'icon_bg_color'  => '#7CB342',
                'sort_order'     => 2,
                'data_step'      => '13',
                'data_title'     => 'Stok Bahan Baku',
                'data_intro'     => '<strong>Jangan sampai kehabisan.</strong> Pantau stok mentah di gudang. Sistem akan memberi tanda jika ada bahan yang perlu segera dibeli.',
            ],
            [
                'feature_key'    => 'suppliers',
                'permission_key' => 'lihat supplier',
                'route_name'     => 'raw-materials.suppliers',
                'label'          => 'Pemasok',
                'description'    => 'Hubungi supplier dengan mudah.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-truck',
                'icon_bg_color'  => '#C0B400',
                'sort_order'     => 3,
                'data_step'      => '14',
                'data_title'     => 'Daftar Pemasok',
                'data_intro'     => '<strong>Hubungi supplier dengan mudah.</strong> Simpan kontak pemasok langganan agar Anda tidak repot mencari nomor saat stok habis.',
            ],
            [
                'feature_key'    => 'reseller_app',
                'permission_key' => 'lihat reseller applications',
                'route_name'     => 'reseller-applications.index',
                'label'          => 'Lamaran Reseller',
                'description'    => 'Perluas jaringan Anda.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-users-three',
                'icon_bg_color'  => '#F4511E',
                'sort_order'     => 4,
                'data_step'      => '15',
                'data_title'     => 'Lamaran Reseller',
                'data_intro'     => '<strong>Perluas jaringan Anda.</strong> Kelola dan seleksi calon mitra reseller yang ingin ikut memasarkan produk Anda di sini.',
            ],
            [
                'feature_key'    => 'production',
                'permission_key' => 'lihat produksi',
                'route_name'     => 'production.index',
                'label'          => 'Produksi',
                'description'    => 'Pantau pembuatan barang.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-factory',
                'icon_bg_color'  => '#00ACC1',
                'sort_order'     => 5,
                'data_step'      => '16',
                'data_title'     => 'Proses Produksi',
                'data_intro'     => '<strong>Pantau pembuatan barang.</strong> Catat kapan bahan baku diolah menjadi produk siap jual agar hitungan stok tetap sinkron.',
            ],
            [
                'feature_key'    => 'stock_opname',
                'permission_key' => 'lihat stock opname',
                'route_name'     => 'stock-opname.index',
                'label'          => 'Stock Opname',
                'description'    => 'Audit fisik barang.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-list-checks',
                'icon_bg_color'  => '#388E3C',
                'sort_order'     => 6,
                'data_step'      => '17',
                'data_title'     => 'Cek Stok (Opname)',
                'data_intro'     => '<strong>Audit fisik barang.</strong> Cocokkan jumlah stok asli di rak dengan data di sistem untuk mencegah kerugian atau kehilangan.',
            ],
            [
                'feature_key'    => 'stock_transfer',
                'permission_key' => 'lihat stock transfer',
                'route_name'     => 'stock-transfers.index',
                'label'          => 'Transfer Stok',
                'description'    => 'Pindah barang antar outlet.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-arrows-left-right',
                'icon_bg_color'  => '#1E88E5',
                'sort_order'     => 7,
                'data_step'      => '18',
                'data_title'     => 'Mutasi Stok',
                'data_intro'     => '<strong>Pindah barang antar outlet.</strong> Catat pengiriman bahan atau produk ke cabang lain agar stok pusat dan cabang tetap terpantau.',
            ],
        ]);

        // ═══════════════════════════════════════════════════
        // CATEGORY 4: Analitik & Laporan
        // ═══════════════════════════════════════════════════
        $cat4 = FeatureCategory::create([
            'name'            => 'Analitik & Laporan',
            'slug'            => 'analytics-reports',
            'description'     => 'Lihat statistik bisnis, unduh laporan, dan pantau transaksi di peta',
            'icon_type'       => 'phosphor',
            'icon_value'      => 'ph-chart-bar',
            'icon_color'      => '#039BE5',
            'gradient_from'   => '#039BE5',
            'gradient_to'     => '#1976D2',
            'is_active'       => true,
            'is_collapsible'  => true,
            'is_default_open' => true,
            'sort_order'      => 4,
            'layout_style'    => 'grid',
        ]);

        $this->seedItems($cat4->id, [
            [
                'feature_key'    => 'dashboard',
                'permission_key' => 'lihat statistik',
                'route_name'     => 'statistics.index',
                'label'          => 'Dashboard & Statistik',
                'description'    => 'Lihat ringkasan usaha.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-chart-bar',
                'icon_bg_color'  => '#039BE5',
                'sort_order'     => 1,
                'data_step'      => '10',
                'data_title'     => 'Dashboard Statistik',
                'data_intro'     => '<strong>Lihat ringkasan usaha.</strong> Tampilkan grafik pertumbuhan omzet dan keuntungan dalam tampilan visual yang mudah dibaca siapa saja.',
            ],
            [
                'feature_key'    => 'reports',
                'permission_key' => 'lihat laporan',
                'route_name'     => 'reports.index',
                'label'          => 'Laporan Keseluruhan',
                'description'    => 'Dokumen evaluasi bisnis.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-file-magnifying-glass',
                'icon_bg_color'  => '#1976D2',
                'sort_order'     => 2,
                'data_step'      => '11',
                'data_title'     => 'Laporan Lengkap',
                'data_intro'     => '<strong>Dokumen evaluasi bisnis.</strong> Unduh laporan detail harian hingga bulanan untuk dibenahi atau dibagikan ke partner bisnis Anda.',
            ],
            [
                'feature_key'    => 'track_transaction_location',
                'permission_key' => 'lihat peta transaksi',
                'route_name'     => 'sales-map.index',
                'label'          => 'Peta Transaksi',
                'description'    => 'Pelacakan operasional real-time.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-map-pin-line',
                'icon_bg_color'  => '#00897B',
                'sort_order'     => 3,
                'data_step'      => '12',
                'data_title'     => 'Peta Transaksi',
                'data_intro'     => '<strong>Pelacakan operasional real-time.</strong> Pantau koordinat transaksi serta rute perjalanan staf dan kasir Anda di atas peta interaktif.',
            ],
        ]);

        // ═══════════════════════════════════════════════════
        // CATEGORY 5: AI & Kecerdasan Bisnis
        // ═══════════════════════════════════════════════════
        $cat5 = FeatureCategory::create([
            'name'            => 'AI & Kecerdasan Bisnis',
            'slug'            => 'ai-tools',
            'description'     => 'Gunakan kekuatan AI untuk analisis, konten, dan strategi bisnis Anda',
            'icon_type'       => 'phosphor',
            'icon_value'      => 'ph-sparkle',
            'icon_color'      => '#5E35B1',
            'gradient_from'   => '#5E35B1',
            'gradient_to'     => '#283593',
            'badge_label'     => 'AI',
            'badge_color'     => '#5E35B1',
            'is_active'       => true,
            'is_collapsible'  => true,
            'is_default_open' => true,
            'sort_order'      => 5,
            'layout_style'    => 'grid',
        ]);

        $this->seedItems($cat5->id, [
            [
                'feature_key'    => 'ai_insights',
                'permission_key' => 'lihat ai insights',
                'route_name'     => 'ai-insights.index',
                'label'          => 'Insight',
                'description'    => 'Saran cerdas dari data.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-sparkle',
                'icon_bg_color'  => '#5E35B1',
                'sort_order'     => 1,
                'data_step'      => '25',
                'data_title'     => 'Lampu Hijau Bisnis',
                'data_intro'     => '<strong>Saran cerdas dari data.</strong> Lihat produk yang paling laku dan dapatkan saran kapan harus menambah stok berdasarkan analisa otomatis kami.',
            ],
            [
                'feature_key'    => 'clara_ai',
                'permission_key' => 'akses clara ai',
                'route_name'     => 'clara-ai.index',
                'label'          => 'Clara AI',
                'description'    => 'Asisten pribadi Anda.',
                'icon_type'      => 'image',
                'icon_value'     => 'assets/image/clara-ai.png',
                'icon_bg_color'  => '#3949AB',
                'sort_order'     => 2,
                'data_step'      => '26',
                'data_title'     => 'Asisten Clara AI',
                'data_intro'     => '<strong>Asisten pribadi Anda.</strong> Tanya Clara apa saja tentang jualan Anda hari ini atau cari ide promo baru melalui obrolan santai.',
            ],
            [
                'feature_key'    => 'ai_insights',
                'permission_key' => null,
                'route_name'     => 'opportunity-map.index',
                'label'          => 'Peta Cuan Lokasi',
                'description'    => 'Analisis lokasi berbasis AI.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-map-trifold',
                'icon_bg_color'  => '#43A047',
                'sort_order'     => 3,
                'data_step'      => '100',
                'data_title'     => 'Peta Cuan Lokasi',
                'data_intro'     => '<strong>Analisis lokasi berbasis AI.</strong> Temukan area bisnis berpotensi tinggi untuk membuka cabang baru berdasarkan peta sebaran usaha.',
            ],
            [
                'feature_key'    => 'clara_ai',
                'permission_key' => 'akses clara ai',
                'route_name'     => 'clara-ai.video-prompt',
                'label'          => 'Video Prompt AI',
                'description'    => 'Generate prompt video sinematik.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-video-camera',
                'icon_bg_color'  => '#283593',
                'sort_order'     => 4,
                'data_step'      => '101',
                'data_title'     => 'Video Prompt AI',
                'data_intro'     => '<strong>Generate prompt video sinematik.</strong> Buat prompt detail untuk tools AI video seperti Runway, Sora, dan Pika berdasarkan data produk Anda.',
            ],
            [
                'feature_key'    => 'clara_ai',
                'permission_key' => 'akses clara ai',
                'route_name'     => 'clara-ai.affiliate-script',
                'label'          => 'Script Generator AI',
                'description'    => 'Generate script affiliate.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-microphone-stage',
                'icon_bg_color'  => '#E64A19',
                'sort_order'     => 5,
                'data_step'      => '102',
                'data_title'     => 'Script Generator AI',
                'data_intro'     => '<strong>Generate script affiliate.</strong> Buat script jualan high-converting untuk TikTok, Instagram, dan YouTube dengan data bisnis Anda.',
            ],
            [
                'feature_key'    => 'clara_ai',
                'permission_key' => 'akses clara ai',
                'route_name'     => 'clara-ai.ads-image-prompt',
                'label'          => 'Image Prompt AI',
                'description'    => 'Generate prompt gambar iklan.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-image-square',
                'icon_bg_color'  => '#00838F',
                'sort_order'     => 6,
                'data_step'      => '103',
                'data_title'     => 'Image Prompt AI',
                'data_intro'     => '<strong>Generate prompt gambar iklan.</strong> Buat prompt untuk Midjourney, DALL·E, dan SDXL yang disesuaikan dengan produk dan brand Anda.',
            ],
            [
                'feature_key'    => 'clara_ai',
                'permission_key' => 'akses clara ai',
                'route_name'     => 'clara-ai.kalkulaba',
                'label'          => 'Kalkulaba AI',
                'description'    => 'Kalkulator laba pintar.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-percent',
                'icon_bg_color'  => '#388E3C',
                'sort_order'     => 7,
                'data_step'      => '104',
                'data_title'     => 'Kalkulaba AI',
                'data_intro'     => '<strong>Kalkulator laba pintar.</strong> Hitung HPP, strategi harga, dan target profit secara otomatis dengan bantuan AI.',
            ],
        ]);

        // ═══════════════════════════════════════════════════
        // CATEGORY 6: Tim & Operasional
        // ═══════════════════════════════════════════════════
        $cat6 = FeatureCategory::create([
            'name'            => 'Tim & Operasional',
            'slug'            => 'team-operations',
            'description'     => 'Kelola tim, tugas harian, aturan outlet, dan manajemen meja',
            'icon_type'       => 'phosphor',
            'icon_value'      => 'ph-identification-card',
            'icon_color'      => '#43A047',
            'gradient_from'   => '#43A047',
            'gradient_to'     => '#00897B',
            'is_active'       => true,
            'is_collapsible'  => true,
            'is_default_open' => true,
            'sort_order'      => 6,
            'layout_style'    => 'grid',
        ]);

        $this->seedItems($cat6->id, [
            [
                'feature_key'    => 'employee_management',
                'permission_key' => 'lihat pegawai',
                'route_name'     => 'employees.index',
                'label'          => 'Pegawai & Hak Akses',
                'description'    => 'Kelola karyawan Anda.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-identification-card',
                'icon_bg_color'  => '#43A047',
                'sort_order'     => 1,
                'data_step'      => '22',
                'data_title'     => 'Tim & Hak Akses',
                'data_intro'     => '<strong>Kelola karyawan Anda.</strong> Daftarkan tim Anda dan tentukan tugas mereka di aplikasi agar operasional lebih tertib dan terkontrol.',
            ],
            [
                'feature_key'    => 'task_management',
                'permission_key' => 'tasks.view',
                'route_name'     => 'tasks.index',
                'label'          => 'Manajemen Tugas',
                'description'    => 'Kerja tim makin kompak.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-clipboard-text',
                'icon_bg_color'  => '#546E7A',
                'sort_order'     => 2,
                'data_step'      => '9',
                'data_title'     => 'Manajemen Tugas',
                'data_intro'     => '<strong>Kerja tim makin kompak.</strong> Berikan tugas ke pegawai, pantau progresnya, dan pastikan tidak ada pekerjaan yang terlewat.',
            ],
            [
                'feature_key'    => 'table_management',
                'permission_key' => 'lihat meja',
                'route_name'     => 'tables.index',
                'label'          => 'Kelola Meja',
                'description'    => 'Atur operasional cafe/resto.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-table',
                'icon_bg_color'  => '#F4511E',
                'sort_order'     => 3,
                'data_step'      => '24',
                'data_title'     => 'Sistem Antrian Meja',
                'data_intro'     => '<strong>Atur operasional cafe/resto.</strong> Kelola nomor meja dan pantau mana yang sedang terisi atau kosong secara real-time dari kasir.',
            ],
            [
                'feature_key'    => 'outlet_policies',
                'permission_key' => 'lihat kebijakan outlet',
                'route_name'     => 'outlet-policies.index',
                'label'          => 'Kebijakan Outlet',
                'description'    => 'Aturan kerja tim.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-notepad',
                'icon_bg_color'  => '#546E7A',
                'sort_order'     => 4,
                'data_step'      => '27',
                'data_title'     => 'SOP & Kebijakan',
                'data_intro'     => '<strong>Aturan kerja tim.</strong> Simpan panduan kerja atau peraturan outlet di sini agar semua pegawai memiliki pemahaman yang sama.',
            ],
        ]);

        // ═══════════════════════════════════════════════════
        // CATEGORY 7: Outlet & Pemasaran
        // ═══════════════════════════════════════════════════
        $cat7 = FeatureCategory::create([
            'name'            => 'Outlet & Pemasaran',
            'slug'            => 'outlet-marketing',
            'description'     => 'Atur identitas toko, buat website, dan kelola mitra reseller',
            'icon_type'       => 'phosphor',
            'icon_value'      => 'ph-buildings',
            'icon_color'      => '#E53935',
            'gradient_from'   => '#E53935',
            'gradient_to'     => '#3949AB',
            'is_active'       => true,
            'is_collapsible'  => true,
            'is_default_open' => true,
            'sort_order'      => 7,
            'layout_style'    => 'grid',
        ]);

        $this->seedItems($cat7->id, [
            [
                'feature_key'       => null,
                'permission_key'    => 'lihat outlet',
                'route_name'        => 'outlets.index',
                'label'             => 'Informasi Outlet',
                'description'       => 'Data utama toko Anda.',
                'icon_type'         => 'phosphor',
                'icon_value'        => 'ph-buildings',
                'icon_bg_color'     => '#E53935',
                'sort_order'        => 1,
                'special_condition' => 'outletInfo',
                'data_step'         => '19',
                'data_title'        => 'Identitas Outlet',
                'data_intro'        => '<strong>Data utama toko Anda.</strong> Lengkapi nama, alamat, dan logo toko Anda agar muncul di nota belanja dan dipercaya pelanggan.',
            ],
            [
                'feature_key'    => 'landing_page',
                'permission_key' => 'lihat landing page',
                'route_name'     => 'landing-pages.index',
                'label'          => 'Landing Page',
                'description'    => 'Go Digital dengan CuanFlow.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-globe-simple',
                'icon_bg_color'  => '#3949AB',
                'sort_order'     => 2,
                'data_step'      => '20',
                'data_title'     => 'Website (Landing Page)',
                'data_intro'     => '<strong>Go Digital dengan CuanFlow.</strong> Buat halaman website katalog sederhana untuk toko Anda agar menarik lebih banyak pelanggan online.',
            ],
            [
                'feature_key'    => 'testimonials',
                'permission_key' => 'lihat testimoni',
                'route_name'     => 'testimonials.index',
                'label'          => 'Testimoni',
                'description'    => 'Kumpulkan kata positif.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-star-half',
                'icon_bg_color'  => '#8E24AA',
                'sort_order'     => 3,
                'data_step'      => '21',
                'data_title'     => 'Ulasan Pelanggan',
                'data_intro'     => '<strong>Kumpulkan kata positif.</strong> Simpan dan tampilkan ulasan terbaik dari pelanggan Anda di website untuk menambah kepercayaan pembeli baru.',
            ],
        ]);

        // ═══════════════════════════════════════════════════
        // CATEGORY 8: Akun & Pengaturan
        // ═══════════════════════════════════════════════════
        $cat8 = FeatureCategory::create([
            'name'            => 'Akun & Pengaturan',
            'slug'            => 'account-settings',
            'description'     => 'Kelola akun, lihat notifikasi, dan atur langganan Anda',
            'icon_type'       => 'phosphor',
            'icon_value'      => 'ph-shield-check',
            'icon_color'      => '#455A64',
            'gradient_from'   => '#455A64',
            'gradient_to'     => '#37474F',
            'is_active'       => true,
            'is_collapsible'  => true,
            'is_default_open' => true,
            'sort_order'      => 8,
            'layout_style'    => 'grid',
        ]);

        $this->seedItems($cat8->id, [
            [
                'feature_key'    => 'account_settings',
                'permission_key' => 'edit profil',
                'route_name'     => 'profile.edit',
                'label'          => 'Pengaturan Akun',
                'description'    => 'Keamanan profil.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-shield-check',
                'icon_bg_color'  => '#455A64',
                'sort_order'     => 1,
                'data_step'      => '28',
                'data_title'     => 'Kelola Akun',
                'data_intro'     => '<strong>Keamanan profil.</strong> Ubah data diri, ganti kata sandi, atau perbarui kontak Anda untuk menjaga keamanan akses sistem.',
            ],
            [
                'feature_key'       => null,
                'permission_key'    => null,
                'route_name'        => 'stock-notifications.index',
                'label'             => 'Notifikasi',
                'description'       => 'Pantau info terbaru.',
                'icon_type'         => 'phosphor',
                'icon_value'        => 'ph-bell-ringing',
                'icon_bg_color'     => '#E53935',
                'sort_order'        => 2,
                'special_condition' => 'alwaysVisible',
                'data_step'         => '31',
                'data_title'        => 'Notifikasi & Peringatan',
                'data_intro'        => '<strong>Pantau info terbaru.</strong> Lihat catatan stok menipis, jadwal kedaluwarsa, atau pengumuman penting lainnya di sini agar bisnis tetap lancar.',
            ],
            [
                'feature_key'    => 'help_faq',
                'permission_key' => 'lihat faq',
                'route_name'     => 'faqs.index',
                'label'          => 'Bantuan & FAQ',
                'description'    => 'Panduan Lengkap.',
                'icon_type'      => 'phosphor',
                'icon_value'     => 'ph-lifebuoy',
                'icon_bg_color'  => '#00897B',
                'sort_order'     => 3,
                'data_step'      => '29',
                'data_title'     => 'Pusat Bantuan',
                'data_intro'     => '<strong>Panduan Lengkap.</strong> Temukan jawaban dari pertanyaan yang sering diajukan atau pelajari cara menggunakan fitur CuanFlow di sini.',
            ],
            [
                'feature_key'       => null,
                'permission_key'    => null,
                'route_name'        => 'subscription.manage',
                'label'             => 'Kelola Langganan',
                'description'       => 'Atur paket Anda.',
                'icon_type'         => 'phosphor',
                'icon_value'        => 'ph-diamond',
                'icon_bg_color'     => '#FB8C00',
                'sort_order'        => 4,
                'special_condition' => 'hasSubscription',
                'data_step'         => '30',
                'data_title'        => 'Kelola Langganan',
                'data_intro'        => '<strong>Atur paket Anda.</strong> Perbarui langganan, lihat riwayat pembayaran, atau ganti paket fitur sesuai kebutuhan bisnis Anda.',
            ],
        ]);
    }

    /**
     * Helper to seed items for a category.
     *
     * @param int   $categoryId
     * @param array $items
     */
    private function seedItems(int $categoryId, array $items): void
    {
        foreach ($items as $item) {
            FeatureCategoryItem::create(array_merge([
                'category_id' => $categoryId,
                'is_active'   => true,
                'is_highlight' => false,
                'open_in_new_tab' => false,
            ], $item));
        }
    }
}
